/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as ApiTestReturnRouteImport } from './routes/api/test-return'
import { Route as ApiTestEmailRouteImport } from './routes/api/test-email'
import { Route as ApiTestDbRouteImport } from './routes/api/test-db'
import { Route as ApiSiteSettingsRouteImport } from './routes/api/site-settings'
import { Route as ApiProductsRouteImport } from './routes/api/products'
import { Route as ApiCheckoutRouteImport } from './routes/api/checkout'
import { Route as ApiUsersSyncRouteImport } from './routes/api/users/sync'
import { Route as ApiUsersProfileRouteImport } from './routes/api/users/profile'
import { Route as ApiUsersOrdersRouteImport } from './routes/api/users/orders'
import { Route as ApiAdminSiteSettingsRouteImport } from './routes/api/admin/site-settings'
import { Route as ApiAdminProductsRouteImport } from './routes/api/admin/products'
import { Route as ApiAdminOrdersRouteImport } from './routes/api/admin/orders'
import { Route as ApiAdminCustomersRouteImport } from './routes/api/admin/customers'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestReturnRoute = ApiTestReturnRouteImport.update({
  id: '/api/test-return',
  path: '/api/test-return',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestEmailRoute = ApiTestEmailRouteImport.update({
  id: '/api/test-email',
  path: '/api/test-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestDbRoute = ApiTestDbRouteImport.update({
  id: '/api/test-db',
  path: '/api/test-db',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSiteSettingsRoute = ApiSiteSettingsRouteImport.update({
  id: '/api/site-settings',
  path: '/api/site-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCheckoutRoute = ApiCheckoutRouteImport.update({
  id: '/api/checkout',
  path: '/api/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersSyncRoute = ApiUsersSyncRouteImport.update({
  id: '/api/users/sync',
  path: '/api/users/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersProfileRoute = ApiUsersProfileRouteImport.update({
  id: '/api/users/profile',
  path: '/api/users/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUsersOrdersRoute = ApiUsersOrdersRouteImport.update({
  id: '/api/users/orders',
  path: '/api/users/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSiteSettingsRoute = ApiAdminSiteSettingsRouteImport.update({
  id: '/api/admin/site-settings',
  path: '/api/admin/site-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProductsRoute = ApiAdminProductsRouteImport.update({
  id: '/api/admin/products',
  path: '/api/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersRoute = ApiAdminOrdersRouteImport.update({
  id: '/api/admin/orders',
  path: '/api/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminCustomersRoute = ApiAdminCustomersRouteImport.update({
  id: '/api/admin/customers',
  path: '/api/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/products': typeof ApiProductsRoute
  '/api/site-settings': typeof ApiSiteSettingsRoute
  '/api/test-db': typeof ApiTestDbRoute
  '/api/test-email': typeof ApiTestEmailRoute
  '/api/test-return': typeof ApiTestReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/api/admin/customers': typeof ApiAdminCustomersRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/products': typeof ApiAdminProductsRoute
  '/api/admin/site-settings': typeof ApiAdminSiteSettingsRoute
  '/api/users/orders': typeof ApiUsersOrdersRoute
  '/api/users/profile': typeof ApiUsersProfileRoute
  '/api/users/sync': typeof ApiUsersSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/products': typeof ApiProductsRoute
  '/api/site-settings': typeof ApiSiteSettingsRoute
  '/api/test-db': typeof ApiTestDbRoute
  '/api/test-email': typeof ApiTestEmailRoute
  '/api/test-return': typeof ApiTestReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/api/admin/customers': typeof ApiAdminCustomersRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/products': typeof ApiAdminProductsRoute
  '/api/admin/site-settings': typeof ApiAdminSiteSettingsRoute
  '/api/users/orders': typeof ApiUsersOrdersRoute
  '/api/users/profile': typeof ApiUsersProfileRoute
  '/api/users/sync': typeof ApiUsersSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/wishlist': typeof WishlistRoute
  '/api/checkout': typeof ApiCheckoutRoute
  '/api/products': typeof ApiProductsRoute
  '/api/site-settings': typeof ApiSiteSettingsRoute
  '/api/test-db': typeof ApiTestDbRoute
  '/api/test-email': typeof ApiTestEmailRoute
  '/api/test-return': typeof ApiTestReturnRoute
  '/product/$id': typeof ProductIdRoute
  '/api/admin/customers': typeof ApiAdminCustomersRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/products': typeof ApiAdminProductsRoute
  '/api/admin/site-settings': typeof ApiAdminSiteSettingsRoute
  '/api/users/orders': typeof ApiUsersOrdersRoute
  '/api/users/profile': typeof ApiUsersProfileRoute
  '/api/users/sync': typeof ApiUsersSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/login'
    | '/shop'
    | '/signup'
    | '/wishlist'
    | '/api/checkout'
    | '/api/products'
    | '/api/site-settings'
    | '/api/test-db'
    | '/api/test-email'
    | '/api/test-return'
    | '/product/$id'
    | '/api/admin/customers'
    | '/api/admin/orders'
    | '/api/admin/products'
    | '/api/admin/site-settings'
    | '/api/users/orders'
    | '/api/users/profile'
    | '/api/users/sync'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/login'
    | '/shop'
    | '/signup'
    | '/wishlist'
    | '/api/checkout'
    | '/api/products'
    | '/api/site-settings'
    | '/api/test-db'
    | '/api/test-email'
    | '/api/test-return'
    | '/product/$id'
    | '/api/admin/customers'
    | '/api/admin/orders'
    | '/api/admin/products'
    | '/api/admin/site-settings'
    | '/api/users/orders'
    | '/api/users/profile'
    | '/api/users/sync'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/cart'
    | '/contact'
    | '/login'
    | '/shop'
    | '/signup'
    | '/wishlist'
    | '/api/checkout'
    | '/api/products'
    | '/api/site-settings'
    | '/api/test-db'
    | '/api/test-email'
    | '/api/test-return'
    | '/product/$id'
    | '/api/admin/customers'
    | '/api/admin/orders'
    | '/api/admin/products'
    | '/api/admin/site-settings'
    | '/api/users/orders'
    | '/api/users/profile'
    | '/api/users/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  WishlistRoute: typeof WishlistRoute
  ApiCheckoutRoute: typeof ApiCheckoutRoute
  ApiProductsRoute: typeof ApiProductsRoute
  ApiSiteSettingsRoute: typeof ApiSiteSettingsRoute
  ApiTestDbRoute: typeof ApiTestDbRoute
  ApiTestEmailRoute: typeof ApiTestEmailRoute
  ApiTestReturnRoute: typeof ApiTestReturnRoute
  ProductIdRoute: typeof ProductIdRoute
  ApiAdminCustomersRoute: typeof ApiAdminCustomersRoute
  ApiAdminOrdersRoute: typeof ApiAdminOrdersRoute
  ApiAdminProductsRoute: typeof ApiAdminProductsRoute
  ApiAdminSiteSettingsRoute: typeof ApiAdminSiteSettingsRoute
  ApiUsersOrdersRoute: typeof ApiUsersOrdersRoute
  ApiUsersProfileRoute: typeof ApiUsersProfileRoute
  ApiUsersSyncRoute: typeof ApiUsersSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-return': {
      id: '/api/test-return'
      path: '/api/test-return'
      fullPath: '/api/test-return'
      preLoaderRoute: typeof ApiTestReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-email': {
      id: '/api/test-email'
      path: '/api/test-email'
      fullPath: '/api/test-email'
      preLoaderRoute: typeof ApiTestEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-db': {
      id: '/api/test-db'
      path: '/api/test-db'
      fullPath: '/api/test-db'
      preLoaderRoute: typeof ApiTestDbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/site-settings': {
      id: '/api/site-settings'
      path: '/api/site-settings'
      fullPath: '/api/site-settings'
      preLoaderRoute: typeof ApiSiteSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/checkout': {
      id: '/api/checkout'
      path: '/api/checkout'
      fullPath: '/api/checkout'
      preLoaderRoute: typeof ApiCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/sync': {
      id: '/api/users/sync'
      path: '/api/users/sync'
      fullPath: '/api/users/sync'
      preLoaderRoute: typeof ApiUsersSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/profile': {
      id: '/api/users/profile'
      path: '/api/users/profile'
      fullPath: '/api/users/profile'
      preLoaderRoute: typeof ApiUsersProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/users/orders': {
      id: '/api/users/orders'
      path: '/api/users/orders'
      fullPath: '/api/users/orders'
      preLoaderRoute: typeof ApiUsersOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/site-settings': {
      id: '/api/admin/site-settings'
      path: '/api/admin/site-settings'
      fullPath: '/api/admin/site-settings'
      preLoaderRoute: typeof ApiAdminSiteSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/products': {
      id: '/api/admin/products'
      path: '/api/admin/products'
      fullPath: '/api/admin/products'
      preLoaderRoute: typeof ApiAdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders': {
      id: '/api/admin/orders'
      path: '/api/admin/orders'
      fullPath: '/api/admin/orders'
      preLoaderRoute: typeof ApiAdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/customers': {
      id: '/api/admin/customers'
      path: '/api/admin/customers'
      fullPath: '/api/admin/customers'
      preLoaderRoute: typeof ApiAdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  WishlistRoute: WishlistRoute,
  ApiCheckoutRoute: ApiCheckoutRoute,
  ApiProductsRoute: ApiProductsRoute,
  ApiSiteSettingsRoute: ApiSiteSettingsRoute,
  ApiTestDbRoute: ApiTestDbRoute,
  ApiTestEmailRoute: ApiTestEmailRoute,
  ApiTestReturnRoute: ApiTestReturnRoute,
  ProductIdRoute: ProductIdRoute,
  ApiAdminCustomersRoute: ApiAdminCustomersRoute,
  ApiAdminOrdersRoute: ApiAdminOrdersRoute,
  ApiAdminProductsRoute: ApiAdminProductsRoute,
  ApiAdminSiteSettingsRoute: ApiAdminSiteSettingsRoute,
  ApiUsersOrdersRoute: ApiUsersOrdersRoute,
  ApiUsersProfileRoute: ApiUsersProfileRoute,
  ApiUsersSyncRoute: ApiUsersSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
